### ISSUE TITLE
Merge Failure on appxbundle

### ISSUE THREAD

**Issue by nograx** [kakone/libVLCX#1]
If the libVLCX NuGet Package is added to the project, the deployment (or the Test with App Certification Kit) of a created appxbundle will fail with "Merge Failure" 0x80070490. If I create single packages for each platform everything is OK.

**Comment by kakone** [comment]
It works for me. You didn't check the ARM architecture checkbox ?

**Comment by nograx** [comment]
I didn't noticed that I can create an appxbundle for arm and one for x86/x64 and upload both to the store. Thanks for the conclusion.
